### PR TITLE
remove graph sorting

### LINKED ISSUE #2170: Graph sorting inflates StringIndex size
**Describe the bug**

The size of the StringIndex increases if `grap.do_sort` is enabled.

Size comparison of `string_index_vals` with `austria-latest.osm.pbf`:

* unsorted: 6.1MB
* sorted: 8.1MB

**To Reproduce**

Run an import with `graph.do_sort: false` and one with `graph.do_sort: true` and compare the size of the resulting `string_index_vals`.

**Expected behavior**

Sorting the graph shouldn't impact the StringIndex size.

### PR DESCRIPTION
**Pull request by karussell**
It would be nice to have this small performance boost but the graph sorting does not work with (complex) turn restrictions (yet), is mostly unused and so for now it is better to remove it. 

Fixes #2170 and #1773.

Was reintroduced in #3177.

### CODE REVIEW

File: core/src/main/java/com/graphhopper/GraphHopper.java [hunk 1]
```diff
@@ -917,17 +906,6 @@ protected void postImportOSM() {
             maxSpeedCalculator.close();
         }
 
-        // Important note: To deal with via-way turn restrictions we introduce artificial edges in OSMReader (#2689).
-        // These are simply copies of real edges. Any further modifications of the graph edges must take care of keeping
```
Comment (easbar) [inline core/src/main/java/com/graphhopper/GraphHopper.java:921]: This comment is still true and not only related to graph sorting so I would keep it.

Comment (easbar) [reply core/src/main/java/com/graphhopper/GraphHopper.java:921]: Maybe at the beginning of postImportOSM? It does not really matter. If you want we can also delete it and just keep it in mind :)
