### PR TITLE
Remove duplicated points at ViaPoints and add getLength to Instructions

### LINKED ISSUE #1216: path details with 'time' returns server error
Example query is [this](https://graphhopper.com/maps/?point=46.796534%2C-71.277752&point=46.820737%2C-71.300411&point=46.807345%2C-71.302643&details=time) and if you move the second point (the only via point) then it starts to get valid.

```
2017-11-09 20:12:27,793 [qtp1373419525-173] WARN  org.eclipse.jetty.server.HttpChannel - /route
java.lang.IllegalStateException: PathDetail list time is inconsistent due to entries 61566 [237, 244] vs. 12510 [245, 249]
        at com.graphhopper.util.PathSimplification.simplify(PathSimplification.java:137)
        at com.graphhopper.util.PathMerger.doWork(PathMerger.java:144)
        at com.graphhopper.routing.template.ViaRoutingTemplate.isReady(ViaRoutingTemplate.java:155)
        at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1072)
```

I.e. 245 is one too much or 244 is one too small.

### PR DESCRIPTION
**Pull request by boldtrn**
This PR fixes #1216 and also addresses parts of #1138.

This PR removes the duplicated point at ViaInstructions. Due to that we could also improve the Instructions and added the `getLength` method to the Instruction, which makes the code easier to read and is a step towards making instructions more similar to PathDetails.

### CODE REVIEW

**Comment by karussell** [comment]
Even better thanks!

File: core/src/main/java/com/graphhopper/util/Instruction.java [hunk 1]
```diff
@@ -238,6 +238,20 @@ void checkOne() {
             throw new IllegalStateException("Instruction must contain at least one point " + toString());
     }
 
+    /**
+     * This method returns the length of an Instruction. The length of an instruction is defined by [the
+     * index of the first point of the next instruction] - [the index of the first point of this instruction].
+     * <p>
+     * In general this will just resolve ot the size of the PointList. This is not true for {@link ViaInstruction} and
```
Comment (karussell) [inline core/src/main/java/com/graphhopper/util/Instruction.java]: Would you write? 'In general this will just resolve ot the size of the PointList except for ...' because the 'last-first' definition still holds for ViaInstructions and I first thought 'this is not true' was referring to the definition

**Comment by karussell** [comment]
Would you mind trying to squash these 3 commits :) ?

**Comment by boldtrn** [comment]
Squashed this PR :)

**Comment by boldtrn** [comment]
> Hope it was easy :)

I am still not a fan of local squashing :). I often have uncommitted changes in my project, but you cannot squash if there are uncommitted changes, so you have to revert them or stash them.
