### PR TITLE
avoid problem with via point and disconnected area

### LINKED ISSUE #1223: Path Details produces ArrayIndexOutOfBoundsException
There is a minor problem when reducing the size and if size is 0

```
 /route
java.lang.ArrayIndexOutOfBoundsException: -1
        at com.graphhopper.util.PointList.add(PointList.java:260)
        at com.graphhopper.util.PathMerger.doWork(PathMerger.java:119)
        at com.graphhopper.routing.template.ViaRoutingTemplate.isReady(ViaRoutingTemplate.java:155)
        at com.graphhopper.GraphHopper.calcPaths(GraphHopper.java:1072)
```

### PR DESCRIPTION
**Pull request by karussell**
fixes #1223

### CODE REVIEW

File: reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java [hunk 1]
```diff
@@ -509,6 +522,8 @@ Graph runAlgo(TestAlgoCollector testCollector, String osmFile,
                     setGraphHopperLocation(graphFile).
                     setEncodingManager(new EncodingManager(importVehicles));
 
+            if (osmFile.contains("krautsand"))
+                hopper.setMinNetworkSize(0, 0);
```
Comment (karussell) [inline reader-osm/src/test/java/com/graphhopper/routing/RoutingAlgorithmWithOSMIT.java]: Not really beautiful but I didn't wanted to introduce a new parameter or method just because of this
