### PR TITLE
Speed up path simplification with path details/instructions - fixed

### LINKED ISSUE #1764: Path simplification is very slow compared to routing
For example for 50 random locations in Germany `PathSimplification.simplify` takes about 80% of the time needed for calculating the route (`GraphHopper.route(request)` for node-based CH), something like: 600 of 720ms.
Apparently, for more locations this gets even worse, e.g. for 500 locations the path simplification takes 55s out of the 57s it takes to calculate the route (>95%). This is maybe expected, because for longer routes CH does not get so much slower, while the path contains a lot more points that need to be simplified.

I added a little measurement file in the `performance_via_routing` branch.

### PR DESCRIPTION
**Pull request by easbar**
This is a revised version of the previously reverted #1782 and should fix #1764.
When trying to update the navigation sdk it turned out the point lists for via- and finish instructions were empty after #1782, which makes problems for both navigation and map matching. For via- and finish-instructions the pointlists must contain a single point even though their `instruction.getLength()` is zero. I have now fixed this and navigation and map-matching tests are green with this change.

### CODE REVIEW

File: core/src/main/java/com/graphhopper/util/PathSimplification.java [hunk 1]
```diff
@@ -25,117 +25,252 @@
...
+                            throw new IllegalStateException("via- and finish-instructions are expected to have zero length");
+                        }
+                        // have to make sure that via instructions and finish instructions contain a single point
+                        // even though their 'instruction length' is zero.
+                        end++;
+                    }
+                    instruction.setPoints(pointList.shallowCopy(start, end, false));
+                }
+            });
+        }
```
Comment (easbar) [inline core/src/main/java/com/graphhopper/util/PathSimplification.java]: This is the fix compared to #1782. For via and finish instructions I increase the interval length, such that they contain a single point. Pretty ugly...

File: reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java [hunk 2]
```diff
@@ -1455,50 +1455,50 @@ public void simplifyWithInstructionsAndPathDetails() {
...
     }
 
     private void assertInstruction(Instruction instruction, String expectedName, String expectedInterval, int expectedLength, int expectedPoints) {
         assertEquals(expectedName, instruction.getName());
-        if (instruction.getPoints() instanceof ShallowImmutablePointList) {
-            assertEquals(expectedInterval, ((ShallowImmutablePointList) instruction.getPoints()).getIntervalString());
-        }
+        assertEquals(expectedInterval, ((ShallowImmutablePointList) instruction.getPoints()).getIntervalString());
         assertEquals(expectedLength, instruction.getLength());
         assertEquals(expectedPoints, instruction.getPoints().size());
```
Comment (easbar) [inline reader-osm/src/test/java/com/graphhopper/GraphHopperIT.java]: Compared to #1782 here I am now testing the instruction length and instructions' point list size separately, because they are different for via and finish instructions.

File: core/src/main/java/com/graphhopper/util/PathSimplification.java (hunk 1 above)
Comment (karussell) [reply core/src/main/java/com/graphhopper/util/PathSimplification.java]: But isn't this similar to how point count and edge count behave? E.g. a path with 1 edge contains 2 points and so 0 edge has 1 point? Hmmh, but yes. A JSON line of 1 point is not allowed.

Comment (easbar) [reply core/src/main/java/com/graphhopper/util/PathSimplification.java]: > But isn't this similar to how point count and edge count behave? E.g. a path with 1 edge contains 2 points and so 0 edge has 1 point? Hmmh, but yes. A JSON line of 1 point is not allowed.

Ah you mean instruction length = number of edges of the interval ? Yes this works, but like you say for a single point its a bit unclear.

**Comment by easbar** [comment]
I think this can be merged, but maybe its better to wait for https://github.com/graphhopper/map-matching/issues/160 and release before merging this.

**Comment by karussell** [comment]
I think I'll just release 1.0-pre7.1 for the map matching bug fix. No need to delay this here? Or do we need something from core?

**Comment by easbar** [comment]
No we can wait a bit until tagging 1.0-pre8

File: core/src/main/java/com/graphhopper/util/PathSimplification.java (hunk 1 above)
Comment (karussell) [reply core/src/main/java/com/graphhopper/util/PathSimplification.java]: Yes. It is similar, so if you have a Via- or FinishInstruction it should still have a location (one point) but no extent or distance.
