### PR TITLE
Fix bug in non-CH AlternativeRoute

### LINKED ISSUE #2566: Alternatives are very slow for LM/AStar+turn costs
map: bayern-210101.osm.pbf: 
route using maps 2 client: http://localhost:3000/?point=49.583276%2C10.991626&point=48.455783%2C12.095752&profile=car
profile: fastest/car

image

|traversal mode|single route|alternatives (max=3)|
|-|-|-|
|node-based|13ms|~800ms|
|edge-based|25ms|~9000ms|

So alternatives take 80 times longer than a single route for node-based. This seems very slow, but at least it still takes less than a second. But for edge-based it is even worse where the slow down is x360 and the response takes so long that its almost not useful anymore.

This is not just special for this route, I just gave an example. I actually saw routes that took tens of seconds, and I did not even try a larger map. Disabling LM makes it even slower.

### PR DESCRIPTION
**Pull request by karussell**
Should fix #2566

Using the fixes of this PR the plateaus show up properly now:

grafik

See the alt_route_debug branch for the necessary changes in MiniGraphUI to see this (using berlin data). Note 1. the two red lines are the best and alternative route in the end, 2. same colors does not mean the plateaus are related and 3. the two block circles are the start and end locations.

Before it was a mess and showed hundreds of potential candidates (many of them were overlapping) that we had to loop through.

The speed improvement should also show up for node-based.

### CODE REVIEW

File: tools/src/main/java/com/graphhopper/tools/Measurement.java [hunk 1]
```diff
@@ -202,10 +202,9 @@ protected void importOSM() {
                     measureRouting(hopper, new QuerySettings("routing_edge", count / 20, isCH, isLM).
                             withInstructions().edgeBased());
                     // unfortunately alt routes are so slow that we cannot really afford many iterations
-                    // actually it is just too slow so we skip it for now
-//                    measureRouting(hopper, new QuerySettings("routing_edge_alt", count / 1000, isCH, isLM).
-//                            edgeBased().alternative()
-//                    );
+                    measureRouting(hopper, new QuerySettings("routing_edge_alt", count / 1000, isCH, isLM).
+                            edgeBased().alternative()
```
Comment (easbar) [inline tools/src/main/java/com/graphhopper/tools/Measurement.java:206]: Currently we use `count=5000`, so `count / 1000` means only five routes will be measured. Could be still useful, or could fluctuate too much. Let's see. Otherwise we could try something like `count / 500`.

File: tools/src/main/java/com/graphhopper/tools/Measurement.java [hunk 2]
```diff
@@ -225,9 +224,8 @@ protected void importOSM() {
                             if (args.getBool("measurement.lm.edge_based", encoder.supportsTurnCosts())) {
                                 measureRouting(hopper, new QuerySettings("routingLM" + activeLMCount + "_edge", count / 20, isCH, isLM).
                                         withInstructions().activeLandmarks(activeLMCount).edgeBased());
-                                // this is too slow
-//                                measureRouting(hopper, new QuerySettings("routingLM" + activeLMCount + "_alt_edge", count / 1000, isCH, isLM).
-//                                        activeLandmarks(activeLMCount).edgeBased().alternative());
+                                measureRouting(hopper, new QuerySettings("routingLM" + activeLMCount + "_alt_edge", count / 1000, isCH, isLM).
+                                        activeLandmarks(activeLMCount).edgeBased().alternative());
```
Comment (easbar) [inline tools/src/main/java/com/graphhopper/tools/Measurement.java:228]: also here maybe we should change this to `count / 500` or so.
