### PR TITLE
Ferry speed fix

### LINKED ISSUE #2532: Better handling for missing ferry duration tags
If there is no duration tag on a ferry we currently use `speed=5km/h`, or even smaller if the distance is below 300m. But for longer distance ferries this seems very likely too slow. Also I think not tagging duration for such longer ferries is a mapping error and if this happens frequently we should report it to OSM.

Also see here: https://github.com/graphhopper/graphhopper/pull/2528/files#r819521430

### PR DESCRIPTION
**Pull request by karussell**
This should fix #2532 and #3138.

An [intermediate commit](https://github.com/graphhopper/graphhopper/pull/3266/changes/8f1b7974166376906b46c324461a9a1c34df7e08) contains a "proper" ferry relation handling which picks the `duration` tag of the relation if the way does not have it but it requires to have the ways also tagged with `route=ferry/shuttle_train` and also often the `duration` tag is missing there too so this does not solve the issue and is rather complicated and so I picked @otbutz suggestion to fix it according to #2532.

### CODE REVIEW

**Comment by otbutz** [comment]
I'd go for a simpler speed heuristic (#3265) and solve the waiting time using turn penalties as proposed in #3264

**Comment by karussell** [comment]
The issue #3264 wouldn't work for bike and foot as we have them deployed via node-based (and turn_penalty only works for edge-based). And also it is not that simple as `ferry_speed` is profile-independent.

File: core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java [hunk 1]
```diff
@@ -32,20 +32,22 @@ static double getSpeed(ReaderWay way) {
             // we reduce the speed to account for waiting time (we increase the duration by 40%)
             return Math.round(speedInKmPerHour / 1.4);
```
Comment (otbutz) [inline core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: Shouldn't this factor also change based on the length of the way? Increasing the duration by 40% for a long ferry route seems excessive.

Comment (karussell) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: Good idea. (This was introduced nearly [13 years ago](https://github.com/graphhopper/graphhopper/commit/7d629b30dd7129a455ac55fe3c17226c5b2a21a1) :))

Comment (otbutz) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: Nothing is more permanent than a temporary solution, I guess :smile:

Comment (karussell) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: Have a look into the latest two commits. I prefer the last one.

Comment (otbutz) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: I like the delay accounting, but having this directly in the OSMReader for all duration tags seems wrong to me. We know that we need to account for boarding in the case of ferries and shuttle trains, but it might be inaccurate for other modes of transportation, such as cable cars.

Comment (karussell) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: Can you elaborate what you mean e.g. an OSM example? Note that currently only ferry and shuttle_train are supported (FerrySpeedCalculator.isFerry==true called via isCalculateWayDistance)

Comment (otbutz) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: While the FerrySpeedCalculator is currently the only consumer of the virtual tag `speed_from_duration`, it gets populated in the neutral `preprocessWay` function of the OSMReader.

Principle of least surprise: I wouldn't expect ferry related time corrections while handling a tag that might also be used for non-ferry routing.

Can we push the delay calculation down to the FerrySpeedCalculator?

Comment (karussell) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: We could remove the artificial tag `speed_from_duration` and use `way_distance` and a new artificial tag like `duration_in_s(ec)` or something.

Comment (karussell) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java]: Have committed a possible solution.

File: core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java [hunk 2]
```diff
@@ -20,32 +20,29 @@ public static boolean isFerry(ReaderWay way) {
...
+        // OSMReader adds the artificial 'duration_in_seconds' and 'way_distance' tags that we can
         // use to set the ferry speed. Otherwise we need to use fallback values.
-        double speedInKmPerHour = way.getTag("speed_from_duration", Double.NaN);
-        if (!Double.isNaN(speedInKmPerHour)) {
-            // we reduce the speed to account for waiting time (we increase the duration by 40%)
-            return Math.round(speedInKmPerHour / 1.4);
+        long durationInSeconds = way.getTag("duration_in_seconds", 0L);
+        if (durationInSeconds > 0) {
+            double waitTime = 30 * 60;
+            double wayDistance = way.getTag("way_distance", Double.NaN);
```
Comment (otbutz) [inline core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java:31]:
```suggestion
            double wayDistance = way.getTag("way_distance", Double.NaN);
            if (Double.isNaN(wayDistance))
                 throw new IllegalStateException("No 'way_distance' set for edge created for way: " + way.getId());
```

Comment (otbutz) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java:31]: btw what's the difference between `edge_distance` and `way_distance` ?

**Comment by otbutz** [comment]
Hijacking the current topic, but would you mind taking a look at #3143 ?

File: core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java (hunk 2 above)
Comment (karussell) [reply core/src/main/java/com/graphhopper/routing/util/FerrySpeedCalculator.java:31]: An OSM way might be split into several GraphHopper edges, hence the edge_distance might be only a smaller part and not the distance that should be used with the `duration` tag, which is for the entire OSM way.

File: core/src/main/java/com/graphhopper/reader/osm/OSMReader.java [hunk 3]
```diff
@@ -516,7 +515,7 @@ protected void preprocessWay(ReaderWay way, WaySegmentParser.CoordinateSupplier
         // tag will be present if 1) isCalculateWayDistance was true for this way, 2) no OSM nodes were missing
         // such that the distance could actually be calculated, 3) there was a duration tag we could parse, and 4) the
         // derived speed was not unrealistically slow.
-        way.setTag("speed_from_duration", speedInKmPerHour);
+        way.setTag("duration:seconds", durationInSeconds);
```
Comment (otbutz) [inline core/src/main/java/com/graphhopper/reader/osm/OSMReader.java]: Should we add the `gh:` prefix like we do it for `gh:barrier_edge`? That namespaces make it much clearer that it's some viirtual GraphHopper populated tag IMHO.

Comment (karussell) [reply core/src/main/java/com/graphhopper/reader/osm/OSMReader.java]: Unfortunately we were not that consistent in the past and would have to change way_distance, edge_distance, ... too
