### PR TITLE
trying to fix problems with incorrectly mapped loop edges

### LINKED ISSUE #1533: Building graph from OSM in case of loop edge fails.
I am getting this error when trying to import this map: https://download.geofabrik.de/europe/germany-140101.osm.pbf. The error occurs due to the recent changes in #1531.
```
Exception in thread "PBF Reader" java.lang.RuntimeException: Unable to read PBF file.
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:50)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.InterruptedException
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:253)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.sendResultsToSink(PbfDecoder.java:96)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.processBlobs(PbfDecoder.java:151)
	at com.graphhopper.reader.osm.pbf.PbfDecoder.run(PbfDecoder.java:162)
	at com.graphhopper.reader.osm.pbf.PbfReader.run(PbfReader.java:47)
	... 1 more
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.put(LinkedBlockingQueue.java:350)
	at com.graphhopper.reader.osm.OSMInputFile.process(OSMInputFile.java:251)
	... 5 more
ERROR [2019-02-04 07:38:59,164] com.graphhopper.reader.osm.OSMReader: Couldn't properly add edge with osm ids:[2603643788, 2603643788, 2569371457, 2517174531]
! java.lang.ArrayIndexOutOfBoundsException: -43
! at com.graphhopper.storage.RAMDataAccess.getInt(RAMDataAccess.java:207)
! at com.graphhopper.reader.PillarInfo.getLatitude(PillarInfo.java:83)
! at com.graphhopper.reader.osm.OSMReader.handlePillarNode(OSMReader.java:768)
! at com.graphhopper.reader.osm.OSMReader.addOSMWay(OSMReader.java:659)
```

### PR DESCRIPTION
**Pull request by karussell**
Fixes #1533

### CODE REVIEW

File: reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java [hunk 1]
```diff
@@ -411,14 +414,31 @@ public void avoidsLoopEdges() {
...
             assertTrue("found a loop", iter.getAdjNode() != iter.getBaseNode());
         }
-        int nodeB = -1;
-        for (int i = 0; i < graph.getNodes(); i++) {
-            if (Math.abs(graph.getNodeAccess().getLat(i) - 12) < 1.e-3) {
-                nodeB = i;
-            }
+        int nodeB = AbstractGraphStorageTester.getIdOf(graph, 12);
+        assertTrue("could not find OSM node B", nodeB > -1);
+        assertEquals(4, GHUtility.count(graph.createEdgeExplorer().setBaseNode(nodeB)));
```
Comment (karussell) [inline reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java]: Here I'm using now the edge counting as the getNeightbors method uses a set which returns 3 instead of the more correct 4. (changing getNeighbors to using a list even with a Collections.sort(list) would make several tests fail and is not worth the effort IMO)

File: reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java [hunk 2]
```diff
@@ -411,14 +414,31 @@ public void avoidsLoopEdges() {
         while (iter.next()) {
             assertTrue("found a loop", iter.getAdjNode() != iter.getBaseNode());
         }
-        int nodeB = -1;
-        for (int i = 0; i < graph.getNodes(); i++) {
-            if (Math.abs(graph.getNodeAccess().getLat(i) - 12) < 1.e-3) {
-                nodeB = i;
-            }
+        int nodeB = AbstractGraphStorageTester.getIdOf(graph, 12);
```
Comment (easbar) [inline reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java]: Oh I did not see this exact code existed already ;)

File: reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java (hunk 1 above)
Comment (easbar) [reply reader-osm/src/test/java/com/graphhopper/reader/osm/OSMReaderTest.java]: Maybe the best would be to check both ? Three neighbors, four edges ? But sure for the nodeB to nodeB loop counting edges is better.

File: reader-osm/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops2.xml [hunk 3]
```diff
@@ -0,0 +1,47 @@
...
+    A - B - E
+    -->
+
+    <node id="1" lat="11" lon="50" uid="A">
+        <tag k="name" v="A"/>
+    </node>
+    <node id="2" lat="12" lon="51" uid="B">
+        <tag k="name" v="B"/>
+    </node>
+    <node id="2" lat="12" lon="51" uid="B2">
```
Comment (easbar) [inline reader-osm/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops2.xml]: Is it on purpose that the id 2 is used twice here ? The way below references a node 6 that is not in the data.

Comment (karussell) [reply reader-osm/src/test/resources/com/graphhopper/reader/osm/test-avoid-loops2.xml]: Oh, will fix.

**Comment by karussell** [comment]
Now I added `Co-authored-by: ...` and still not working. Really strange.

**Comment by karussell** [comment]
It might be because I was missing two empty lines ... WTH ...

> Tip: If you're using a text editor on the command line to type your commit message, ensure there are two lines between the end of your commit description and the Co-authored-by: commit trailer.
